const fullName = 'Eduardo Gallegos';
const isCool = false;
const totalPets = 3;
const unknown = null;
const never = undefined;
console.log('value of fullName:', fullName);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('value of unknown:', unknown);
console.log('value of never:', never);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
console.log('typeof unknown:', typeof unknown);
console.log('typeof never:', typeof never);
