var width = 3;
var height = 2;
var area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
var bill = 15;
var payment = 10;
var change = bill - payment;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
var quizzes = 40;
var midterm = 60;
var final = 98;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
var firstName = 'Eduardo ';
var lastName = 'Gallegos';
var fullName = firstName + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
var ph = 10;
var isAcidic = ph < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
var headCount = 12;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
var motto = fullName + ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
